[default]
workshop = [
  # CBA_A3
  "450814997",
  # ACE
  "463939057",
  # 3den Enhanced
  "623475643"
]

[aegis]
extends = "default"
workshop = [
  # Arma 3 Aegis
  "949252631",
  # Western Sahara
  "2636962953"
]

[rhs]
extends = "default"
workshop = [
  # RHSUSAF
  "843577117",
  # RHSAFRF
  "843425103",
  # RHSGREF
  "843593391",
  # RHSSAF
  "843632231"
]
